volumes:
  mongo_data:
    name: mta_mongo_data

services:
  mongo:
    image: mongo
    container_name: mta
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
